### PR TITLE
add broadcastMessage

### PR DESCRIPTION
**Pull request by thijstriemstra**
I wanted to send some custom messages to the client so I added a method to do that.

### CODE REVIEW

**Comment by srwi** [comment]
Thank you for the handy addition!

**Comment by thijstriemstra** [comment]
thanks! Could you make a new release?

**Comment by srwi** [comment]
I'll address #23 first and then do a release, probably on the weekend.

**Comment by thijstriemstra** [comment]
Could you also publish it @srwi, https://www.ardu-badge.com/FastLEDHub for example is still on the old version.

**Pull request merged**
